ci(check): detect force push change

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -3,10 +3,61 @@ name: Check
 on: push
 
 jobs:
+  detect_code_change:
+    name: Detect code change
+    runs-on: ubuntu-latest
+    permissions:
+      actions: read
+      contents: read
+    outputs:
+      changed: ${{ steps.detect_code_change.outputs.changed }}
+    steps:
+      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
+        with:
+          fetch-depth: 1
+      - name: Detect code changes
+        id: detect_code_change
+        run: |
+          before=${{ github.event.before }}
+          git fetch --depth=1 origin $before
+          git diff --quiet $before ${{ github.event.head }} || echo "changed=true" >> "$GITHUB_OUTPUT"
+      - name: Output previous run
+        if: steps.detect_code_change.outputs.changed != 'true'
+        run: |
+          query='.workflow_runs[] | select(.head_sha == "${{ github.event.before }}")'
+          prev_run="$(gh api repos/${{ github.repository }}/actions/runs --jq "$query" | head -n 1)"
+          prev_run_id="$(jq -r '.id' <<< "$prev_run")"
+          prev_run_html_url="$(jq -r '.html_url' <<< "$prev_run")"
+
+          while true; do
+            status="$(jq -r '.status' <<< "$prev_run")"
+            conclusion="$(jq -r '.conclusion' <<< "$prev_run")"
+
+            if [[ "$status" == "completed" ]]; then
+              echo "Previous run completed with conclusion: $conclusion"
+              break
+            fi
+            sleep 10
+
+            prev_run="$(gh api repos/${{ github.repository }}/actions/runs/$prev_run_id | head -n 1)"
+          done
+
+          echo "::notice title=No changes since previous run::Previous run: $prev_run_html_url"
+          if [[ "$conclusion" != "success" ]]; then
+            echo "::error::Previous run failed with conclusion: $conclusion"
+            exit 1
+          fi
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
   check:
     name: Check
+    needs: detect_code_change
+    if: needs.detect_code_change.outputs.changed == 'true'
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
+        with:
+          fetch-depth: 1
       - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31.10.6
       - run: nix flake check --all-systems
